version: 1.0.0.{build}

skip_tags: true

configuration: DebugNoVsix

init:
  - git config --global core.autocrlf true

clone_folder: c:\projects\code-cracker

shallow_clone: false

clone_depth: 5

environment:
  COVERALLS_REPO_TOKEN:
    secure: 9qsI9p9EPYyYoEetOcoQ76A7zfQRdstXY81MQFnX1Zpddtc0CrQThKAFPUba12m4

before_build:
  - ps: >-
      $env:path="C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\CommonExtensions\Microsoft\TestWindow;C:\Program Files (x86)\Microsoft SDKs\F#\4.0\Framework\v4.0\;C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.1;C:\Program Files (x86)\MSBuild\14.0\bin;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools;C:\Windows\Microsoft.NET\Framework\v4.0.30319;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\VCPackages;C:\Program Files (x86)\HTML Help Workshop;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Team Tools\Performance Tools;C:\Program Files (x86)\Windows Kits\8.1\bin\x86;C:\Program Files (x86)\Microsoft SDKs\Windows\v8.1A\bin\NETFX 4.5.1 Tools\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.1\;$env:path"

      . .\build.ps1 Prepare-Build


build_script:
  - ps: . .\build.ps1 Build-Only


after_build:
  - ps: >-
      . .\build.ps1 Pack-Nuget

test_script:
  - ps: >-
      . .\build.ps1 Test


after_test:
  - ps: >-
      . ".\test\CSharp\AnalyzeCecil.ps1"


artifacts:
  - path: src
    name: src
  - path: test
    name: test
  - path: log
    name: log

deploy:
- provider: NuGet
  api_key:
    secure: s1aIT1sGbIeG5Ccgree7K+k/h7LOSzPfJOrsWcCuzgFGrcuexPZUwX/CfYnU9w4v
  skip_symbols: true
  on:
    branch: release
- provider: NuGet
  server: https://www.myget.org/F/codecrackerbuild/api/v2/package
  api_key:
    secure: 42eslsnaZIIcMVVaeC9Qu5NI9yjzLzHWYUGl0HLhl0YurivQezpMyJOwgSVjiGmj
  skip_symbols: true
  on:
    branch: master
- provider: NuGet
  server: https://www.myget.org/F/codecrackerbuild/api/v2/package
  api_key:
    secure: 42eslsnaZIIcMVVaeC9Qu5NI9yjzLzHWYUGl0HLhl0YurivQezpMyJOwgSVjiGmj
  skip_symbols: true
  on:
    branch: vnext

notifications:
- provider: Email
  to:
  - cds@cds-software.com.br
  - elemarjr@gmail.com
  - giggio@giggio.net
  subject: CodeCracker Build
  on_build_success: false
  on_build_failure: false
  on_build_status_changed: true
- provider: Slack
  auth_token:
    secure: 27j6KWmjrx8b6KiDamj8lSDkJDEfIefQO4Cgt3OZF+c8u/RqTkSrfeG5GNhcEG0kl861mTS07J4IU/FvHTC1PQ==
  channel: general
  on_build_success: false
  on_build_failure: false
  on_build_status_changed: true